(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.ChatGPTDiagnostics=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const EVENT_SCHEMA_VERSION=1,REPORT_SCHEMA_VERSION=1,MAX_EVENTS=200,MAX_EVENT_AGE_MS=7*864e5,AGGREGATE_WINDOW_MS=3e4;
  const STORAGE_KEYS={EVENTS:"diagnosticEventsV1",META:"diagnosticMetaV1",SALT:"diagnosticSaltV1",LATEST_PAGES:"latestPageDiagnosticsV1"};
  const RESULTS=new Set(["ok","failed","blocked","paused","ignored","recovered","started","completed"]);
  const cleanText=(value,max=160)=>String(value||"").replace(/\s+/g," ").trim().slice(0,max);
  function sanitizeText(value,max=160){return cleanText(cleanText(value,Math.max(max*3,480))
    .replace(/https?:\/\/[^\s)\]}>,]+/gi,"[url]")
    .replace(/\bBearer\s+[A-Za-z0-9._~+\/-]+=*/gi,"Bearer [redacted]")
    .replace(/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g,"[jwt]")
    .replace(/\b[A-Z]:\\(?:[^\s\\]+\\)*[^\s]*/gi,"[local-path]")
    .replace(/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b/g,"[email]")
    .replace(/\b(api[_-]?key|token|secret|password|cookie|authorization)\s*[:=]\s*[^\s,;]+/gi,"$1=[redacted]")
    .replace(/\b(?:sk|ghp|github_pat|xox[baprs])-?[A-Za-z0-9_-]{16,}\b/g,"[secret]")
    .replace(/\b[0-9a-f]{32,}\b/gi,"[identifier]"),max)}
  function createId(prefix="id"){const random=crypto?.randomUUID?.().slice(0,12)||Math.random().toString(36).slice(2,14);return`${prefix}-${Date.now().toString(36)}-${random}`}
  function normalizeEvent(event={},now=Date.now()){return{schemaVersion:EVENT_SCHEMA_VERSION,id:cleanText(event.id||createId("diag"),80),type:cleanText(event.type||"diagnostics.unknown",80),result:RESULTS.has(event.result)?event.result:"ok",reasonCode:cleanText(event.reasonCode,80),module:cleanText(event.module||"extension",40),operation:cleanText(event.operation,60),pageAlias:cleanText(event.pageAlias,40),sessionAlias:cleanText(event.sessionAlias,40),summary:sanitizeText(event.summary,160),count:Math.max(1,Number(event.count||1)),firstSeenAt:Number(event.firstSeenAt||event.timestamp||now),lastSeenAt:Number(event.lastSeenAt||event.timestamp||now)}}
  function pruneEvents(events,now=Date.now()){const cutoff=now-MAX_EVENT_AGE_MS;return(Array.isArray(events)?events:[]).map((event)=>normalizeEvent(event,now)).filter((event)=>event.lastSeenAt>=cutoff).sort((a,b)=>a.lastSeenAt-b.lastSeenAt).slice(-MAX_EVENTS)}
  function mergeEvent(events,incoming,now=Date.now()){const item=normalizeEvent(incoming,now),list=pruneEvents(events,now),last=list.at(-1);if(last&&last.type===item.type&&last.result===item.result&&last.reasonCode===item.reasonCode&&last.module===item.module&&last.pageAlias===item.pageAlias&&last.sessionAlias===item.sessionAlias&&now-last.lastSeenAt<=AGGREGATE_WINDOW_MS){last.count+=item.count;last.lastSeenAt=now;if(item.summary)last.summary=item.summary}else list.push(item);return pruneEvents(list,now)}
  function createSalt(){const bytes=new Uint8Array(16);crypto?.getRandomValues?.(bytes);return bytes.some(Boolean)?[...bytes].map((v)=>v.toString(16).padStart(2,"0")).join(""):`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}
  async function hashIdentifier(salt,value,prefix="id"){const input=`${salt||""}:${value||""}`;if(crypto?.subtle&&typeof TextEncoder!=="undefined"){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input));return`${prefix}_${[...new Uint8Array(digest)].slice(0,6).map((v)=>v.toString(16).padStart(2,"0")).join("")}`}let hash=2166136261;for(let i=0;i<input.length;i++){hash^=input.charCodeAt(i);hash=Math.imul(hash,16777619)}return`${prefix}_${(hash>>>0).toString(16).padStart(8,"0")}`}
  const caps=(value={})=>({canTrackTask:Boolean(value.canTrackTask),canDetectCompletion:Boolean(value.canDetectCompletion),canAdmitQueue:Boolean(value.canAdmitQueue),canDispatchQueue:Boolean(value.canDispatchQueue),canWriteComposer:Boolean(value.canWriteComposer),canClickSend:Boolean(value.canClickSend)});
  function normalizePublicSnapshot(s){if(!s||typeof s!=="object")return null;return{schemaVersion:Math.max(1,Number(s.schemaVersion||1)),observedAt:Number(s.observedAt||0),pageReady:Boolean(s.pageReady),supportStatus:cleanText(s.supportStatus||"unsupported",24),routeType:cleanText(s.routeType||"unknown",40),compatibility:cleanText(s.compatibility||"unsupported",24),reasonCodes:[...new Set((s.reasonCodes||[]).map((v)=>cleanText(v,80)).filter(Boolean))],capabilities:caps(s.capabilities),composer:{exists:Boolean(s.composer?.exists),ready:Boolean(s.composer?.ready),empty:Boolean(s.composer?.empty),textLengthBucket:cleanText(s.composer?.textLengthBucket||"empty",20),visibleCount:Math.max(0,Number(s.composer?.visibleCount||0)),ambiguous:Boolean(s.composer?.ambiguous)},controls:{send:{exists:Boolean(s.controls?.send?.exists),enabled:Boolean(s.controls?.send?.enabled)},stopVisible:Boolean(s.controls?.stopVisible),waitingAction:Boolean(s.controls?.waitingAction),busy:Boolean(s.controls?.busy)},error:{visible:Boolean(s.error?.visible)},messages:{userCount:Math.max(0,Number(s.messages?.userCount||0)),assistantCount:Math.max(0,Number(s.messages?.assistantCount||0)),latestAssistantHasCopyAction:Boolean(s.messages?.latestAssistantHasCopyAction),copyActionCount:Math.max(0,Number(s.messages?.copyActionCount||0))}}}
  function bucketTotalText(items){const total=(items||[]).reduce((sum,item)=>sum+Math.max(0,Number(item?.textLength||0)),0);return!total?"empty":total<1e3?"<1k":total<1e4?"1k-10k":total<1e5?"10k-100k":">100k"}
  function buildQueueSummary(index={},leases={}){const queues=Object.values(index||{}),items=queues.flatMap((q)=>Array.isArray(q?.items)?q.items:[]),itemCounts={pending:0,dispatching:0,running:0,completed:0,failed:0};items.forEach((item)=>{if(item?.status in itemCounts)itemCounts[item.status]++});return{queueCount:queues.length,pausedQueueCount:queues.filter((q)=>q?.paused).length,itemCounts,activeItemCount:queues.filter((q)=>q?.activeItemId).length,leaseCount:Object.keys(leases||{}).length,totalTextBucket:bucketTotalText(items)}}
  function buildTaskSummary(tasks=[]){const counts={running:0,waiting_action:0,completed:0,failed:0,cancelled:0},recent=[];(tasks||[]).forEach((task)=>{if(task?.status in counts)counts[task.status]++;if(recent.length<20)recent.push({alias:`task-${recent.length+1}`,status:cleanText(task?.status||"unknown",30),observerMode:cleanText(task?.observerMode||"none",30),startedAt:Number(task?.startedAt||0),updatedAt:Number(task?.updatedAt||0),finishedAt:task?.finishedAt?Number(task.finishedAt):null,stopReason:sanitizeText(task?.stopReason,120)})});return{counts,recent}}
  function deriveHealth(page,permission,index){return{page:page?cleanText(page.compatibility||page.supportStatus||"unknown",30):"no_page",notifications:permission==="granted"?"healthy":"blocked",tasks:"available",queue:Object.values(index||{}).some((q)=>q?.paused)?"paused":"healthy"}}
  function buildReport({extensionVersion="0.0.0",manifestVersion=3,browserMajorVersion="unknown",platform="unknown",notificationPermission="unknown",tasks=[],queueIndex={},leases={},currentPage=null,events=[],generatedAt=Date.now()}={}){return{schema:"gpt-notice-diagnostics",schemaVersion:REPORT_SCHEMA_VERSION,generatedAt,privacy:"本报告按允许列表生成，不含聊天正文、Cookie、Token、完整 URL、原始会话 ID、Tab ID、设备名或本地路径。",extension:{version:cleanText(extensionVersion,30),manifestVersion:Math.max(2,Number(manifestVersion||3))},environment:{browserMajorVersion:cleanText(browserMajorVersion||"unknown",20),platform:cleanText(platform||"unknown",30),notificationPermission:cleanText(notificationPermission||"unknown",30)},health:deriveHealth(currentPage,notificationPermission,queueIndex),currentPage:normalizePublicSnapshot(currentPage),tasks:buildTaskSummary(tasks),queues:buildQueueSummary(queueIndex,leases),events:pruneEvents(events,generatedAt).slice(-100)}}
  function toMarkdown(report){const r=report||buildReport(),page=r.currentPage,reasons=page?.reasonCodes?.join(", ")||"无",counts=r.tasks?.counts||{},queue=r.queues||{},events=(r.events||[]).slice(-20).reverse();const lines=["# gpt-notice 诊断摘要","",`- 生成时间：${new Date(r.generatedAt).toISOString()}`,`- 扩展版本：${r.extension?.version||"unknown"}`,`- 浏览器主版本：${r.environment?.browserMajorVersion||"unknown"}`,`- 平台：${r.environment?.platform||"unknown"}`,`- 通知权限：${r.environment?.notificationPermission||"unknown"}`,`- 当前页面：${page?`${page.supportStatus}/${page.compatibility}/${page.routeType}`:"无活动工作页面"}`,`- 页面原因：${reasons}`,`- 活动任务：${Number(counts.running||0)+Number(counts.waiting_action||0)}`,`- 队列：${queue.queueCount||0} 个，暂停 ${queue.pausedQueueCount||0} 个，等待 ${queue.itemCounts?.pending||0} 条`,"","## 最近诊断事件",""];if(!events.length)lines.push("暂无诊断事件。");else events.forEach((e)=>lines.push(`- ${new Date(e.lastSeenAt).toISOString()} · ${e.type} · ${e.result}${e.reasonCode?` · ${e.reasonCode}`:""}${e.count>1?` ×${e.count}`:""}`));lines.push("",`> ${r.privacy}`);return lines.join("\n")}
  return{EVENT_SCHEMA_VERSION,REPORT_SCHEMA_VERSION,MAX_EVENTS,MAX_EVENT_AGE_MS,STORAGE_KEYS,cleanText,sanitizeText,normalizeEvent,mergeEvent,pruneEvents,createSalt,hashIdentifier,normalizePublicSnapshot,buildQueueSummary,buildTaskSummary,buildReport,toMarkdown}
});
